[project]
name = "template-aidl-w02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

# [project.scripts]
# template-aidl-w02 = "template_aidl_w02:main"

# [build-system]
# requires = ["uv_build>=0.12.10,<0.13.0"]
# build-backend = "uv_build"

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchvision = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
